### ISSUE TITLE
"unexpected -vV format" panic from rustc-version, update rustc-version dependency?

### ISSUE THREAD

**Issue by bootchk** [japaric/xargo#170]
Running xargo I get:

thread 'main' panicked at 'unexpected -vV format', .home/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc_version-0.1.7/src/lib.rs:126:4
stack backtrace:
   0:   ....
   5: std::panicking::begin_panic
   6: rustc_version::version_meta_for
   7: rustc_version::version_meta
   8: xargo::run
   9: xargo::main
  10: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  11: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  12: __libc_start_main
  13: _start

 https://github.com/Kimundi/rustc-version-rs/issues/12  seems to suggest that this might be fixed by version 0.2 "This is a bug that is fixed in the newest 0.2 release of this crate" .  Maybe xargo should "Update rustc_version dep to 0.2".

I am a rust rookie, following your tutorial to compile for ARM.  Dev environment is in a vagga container, and the environment may well be flawed.  My report could be spurious.  I don't understand the root cause and haven't tried changing the dependency.

**Comment by bootchk** [comment]
So I hacked at xargo:

- !Sh "sed -i 's/0.1.7/0.2.0/g' /work/xargo/Cargo.toml"
- !Sh "sed -i 's/rustc::version()/rustc::version().unwrap()/g' /work/xargo/src/main.rs"

But this updating rustc-version doesn't seem to fix it,  now I get:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnexpectedVersionFormat', /checkout/src/libcore/result.rs:906:4
stack backtrace:
   0:  ...
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
  10: xargo::run

But rustc -vV returns:

rustc 1.22.0-nightly (0e6f4cf51 2017-09-27)
binary: rustc
commit-hash: 0e6f4cf51cd3b799fb057956f8e733d16605d09b
commit-date: 2017-09-27
host: x86_64-unknown-linux-gnu
release: 1.22.0-nightly
LLVM version: 4.0

I will keep exploring.

**Comment by bootchk** [comment]
Sorry, spurious.  Flaw in the vagga container.
